### ISSUE TITLE
Lots of dependencies are old enough to require nodejs 0.8.0

### ISSUE THREAD

**Issue by giacecco** [dscape/nano#166]
I get these warnings when installing nano using npm:

```
(...)
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.22","npm":"1.3.15"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current {"node":"v0.10.22","npm":"1.3.15"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.22","npm":"1.3.15"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.22","npm":"1.3.15"})
(...)
```

It looks like many of the libraries nano depends upon have not been maintained for a while. Would you say this is a liability until nano is updated to do without?

Thanks,

Giacecco

**Comment by Kevin-Allain** [comment]
Hello, I am currently facing the same issue:

npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
npm WARN engine request@2.55.0: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine form-data@0.2.0: wanted: {"node":">= 0.8"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine mime-types@2.0.11: wanted: {"node":">= 0.6"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine tough-cookie@1.1.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine http-signature@0.10.1: wanted: {"node":">=0.8"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine hawk@2.3.1: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine combined-stream@0.0.7: wanted: {"node":">= 0.8"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine har-validator@1.7.0: wanted: {"node":">=0.10"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine delayed-stream@0.0.5: wanted: {"node":">=0.4.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine mime-db@1.9.1: wanted: {"node":">= 0.6"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine ctype@0.5.3: wanted: {"node":">= 0.4"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine assert-plus@0.1.5: wanted: {"node":">=0.8"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine asn1@0.1.11: wanted: {"node":">=0.4.9"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine commander@2.8.1: wanted: {"node":">= 0.6.x"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine chalk@1.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine boom@2.7.1: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine hoek@2.13.0: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine cryptiles@2.0.4: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine sntp@1.0.9: wanted: {"node":">=0.8.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine has-ansi@1.0.3: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine strip-ansi@2.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine xtend@4.0.0: wanted: {"node":">=0.4"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})

npm WARN engine ansi-regex@1.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine ansi-regex@1.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})
npm WARN engine get-stdin@4.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.9.9-pre","npm":"2.9.1"})



Still I downloaded the latest version from nodejs.org.

What should I do ?

**Comment by jo** [comment]
Please make sure you're actually an up to date npm. This looks like node 0.9.9-pre.
