### ISSUE TITLE
Updates fail if nano is used in 'parallel' execution models using caolan/async

### ISSUE THREAD

**Issue by giacecco** [dscape/nano#167]
See the simple code [here](https://github.com/giacecco/datagovuk-monitor/blob/7305d2ed975f42b3b263232333c20aa16c600496/test.js#L32). 

If I set anything higher than '1' as the size of the pool of functions to be called in parallel using [caolan/async](https://github.com/caolan/async)'s _eachLimit_ function, sometime in the process the updates fail with the error shown below. 

```
{ [Error: error happened in your connection]
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'connect',
  description: 'connect EADDRNOTAVAIL',
  stacktrace: 
   [ 'Error: connect EADDRNOTAVAIL',
     '    at errnoException (net.js:901:11)',
     '    at connect (net.js:764:19)',
     '    at net.js:842:9',
     '    at asyncCallback (dns.js:68:16)',
     '    at Object.onanswer [as oncomplete] (dns.js:121:9)' ] }
```

Any hint? Perhaps nano is not supposed to be used for more than one update operation, while we're still waiting for the callback for the previous one?

I am using a fresh install of couchdb 1.5.0-1 on MacOS through Homebrew.

Thanks!

Giacecco

**Comment by samdutton** [comment]
I get the same error intermittently working from localhost, attempting to insert 525 docs with `db.insert`: `error happened in your connection`. Sometimes it goes wrong, sometimes it doesn't.

I'm attempting to download video data from the YouTube API, then add the data for each video as a doc in a database:

    function addVideosToDatabase() {
      var nano = require('nano')('http://localhost:5984');
      nano.db.destroy('database', function() {
        nano.db.create('database', function() {
          var database = nano.use('database');
          for (var i = 0; i !== allVideos.length; ++i) {
            insertVideo(database, allVideos[i]);
          }
        });
      });
    }

    function insertVideo(db, video) {
      db.insert(video, video.id,
        function(err/*, body , header */) {
          if (err) {
            console.log('db.insert error: ', err.message);
            return;
          }
        });
    }

The JSON for each video looks like this: 

    {
      "kind": "youtube#playlistItem",
      "etag": "\"9iWEWaGPvvCMMVNTPHF9GiusHJA/L-KjfesS-9dnfeyYToxvnvnxcH0\"",
      "id": "UUHcm5c6gEhmggA4U_I30U3Z5Tw8i6AN4L",
      "snippet": {
        "publishedAt": "2015-03-12T22:43:59.000Z",
        "channelId": "UCVHFbqXqoYvEWM1Ddxl0QDg",
        "title": "Haystack TV Doubles Engagement with Android TV",
        "description": "Haystack TV built a scalable business with six employees and Android TV. Two weeks was all it took for them to bring their mobile app to the big screen. That includes building an immersive, cinematic UI (a task greatly simplified by the Android framework). Watch how they grew their weekly average viewing time from 40 minutes to 80. Now, their business is growing at 40% per month. You can too.\n\nLearn more about Android TV at developer.android.com/tv. To get more tips, check out The Secrets to App Success on Google Play [ebook] (http://goo.gl/63LtjD)\n\n#android #googleplay #developerstory #featured",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/MPnH7h12h0U/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/MPnH7h12h0U/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/MPnH7h12h0U/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/MPnH7h12h0U/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/MPnH7h12h0U/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "Android Developers",
        "playlistId": "UUVHFbqXqoYvEWM1Ddxl0QDg",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "MPnH7h12h0U"
        }
      }
    }

**Comment by dscape** [comment]
Hi Sam,

It seems like maybe following these tutorials can perhaps help?

http://nodetuts.com/series/asynchronous-programming.html

Alternatively maybe using a off the shelf module like `require('async')`?

Sometimes it's hard to keep track of what the event loop is doing, and it's probably why this is happening. I don't think it has necessarily something to do with nano though, do you disagree? 

If I'm wrong I apologize, was trying to give you a quick response but am in meeting all afternoon so couldnt pay too much of a close attention (lucky me huh?)

Thanks for using nano and let me know how it goes.

**Comment by samdutton** [comment]
Hi – no problem, thanks for the link. 

Seems to perform well enough using the callback technique I described, so I'll stick with that for the moment.
