### ISSUE TITLE
List breaking changes for the 6.0.0 release

### ISSUE THREAD

**Issue by anowak** [dscape/nano#235]
The 6.0.0 release introduces a change that will probably break a lot of client code, namely it removes `status_code` and `status-code` fields from the response objects and replaces it with `statusCode`. While it makes a lot of sense (e.g. making it more consistent with the style used by `request`), it is very hard to spot, especially that `nano` doesn't have release notes.

It would be great to save people a lot of headache by adding a short section to the README containing all the breaking changes like this. I believe that some naming changes were also introduced elsewhere (`responseType`?), but I don't follow the development closely enough to compile such list myself.

**Comment by dscape** [comment]
@anowak that's a great idea. Please do feel free to send in a PR with this, unfortunately I never got to it and it's not in the pipeline
