### ISSUE TITLE
Better documentation for params

### ISSUE THREAD

**Issue by varunnaik** [dscape/nano#241]
Parts of the API are hard to understand, and require experimentation: For example
```nano.db.changes(name, [params], [callback])```
I am not sure whether params here should be a string or an object. Both of these fail when I try them. In general, most of the places where we can pass params to a function call, it is not clear what the format of the params should be and what options are possible.

Is it possible to run the changes feed through a filter and get a list of filtered results, i.e., get the results of ```db/_changes?filter=app/important```? This is what I'm trying to do?

**Comment by dscape** [comment]
Feel free to send in a PR
