### ISSUE TITLE
Use nano in browser

### ISSUE THREAD

**Issue by natcohen** [dscape/nano#244]
Would be awesome if we could use nano in the browser! Any plan to do it?

**Comment by jo** [comment]
Nano is build on top of [request](https://github.com/request/request), a HTTP client for node. Therefore it is not possible to use nano directly in the browser.

You can [browserify](http://browserify.org/) nano with
```sh
browserify lib/nano.js -o nano.js
```
but be aware that the result is very huge (> 1M).
