### ISSUE TITLE
Keep alive agent instructions in the README does not work

### ISSUE THREAD

**Issue by kanongil** [dscape/nano#246]
In this section: https://github.com/dscape/nano/blob/master/README.md#pool-size-and-open-sockets.

**Comment by dscape** [comment]
Can you please send in a test case so we can try this?

**Comment by kanongil** [comment]
A test case where I verify that keep-alive works (and is not just set in the header) that works in both node 0.10 and 0.11+: _No_

I _can_ tell you what I do in 0.11+:
```javascript
var nano = require('nano')({
  url: 'http://localhost:5984/foo',
  requestDefaults: {
    jar: false,
    agentOptions: {
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 50,
    }
  }
});
```

Note that this means that your process will not exit automatically since `http.Agent#destroy()` is never called.

I can also tell you that you are better of removing the section from the doc, than keeping it, as it has never ever worked since `request` has no `agent` option.

**Comment by dscape** [comment]
@mikeal was this a change in request?
