### ISSUE TITLE
Is it possible to get the mimetype when getting attachments?

### ISSUE THREAD

**Issue by jandrieu** [dscape/nano#248]
The API seems to just have the body of the attachment in the callback arguments for db.attachment.get. How can I get the content-type?  Would it be possible with db.request?

**Comment by dscape** [comment]
Isn't this in the response headers?

See:
* http://docs.couchdb.org/en/latest/api/document/attachments.html

If this does not solve your issue please reopen with some working code so I can easily reproduce and help you!

**Comment by jandrieu** [comment]
Ah... Until I dove into what relax is doing, I didn't see that there is a third parameter in a successful callback:

```javascript
  return callback(null, parsed, rh);
```

Because the docs just show the body.
```javascript
alice.attachment.get('rabbit', 'rabbit.png', function(err, body) {
  if (!err) {
    fs.writeFile('rabbit.png', body);
  }
});
```


It would be cool to have something to that effect in the documentation.

**Comment by jandrieu** [comment]
p.s.
It looks like I can't reopen an issue if you close it.

**Comment by dscape** [comment]
You can just send the pull request with the fixes if you like. 

I think it would be best to have a general section explaining that this is the signature of all callback functions, instead of specifying one by one.

What do you think?

https://github.com/dscape/nano#dbheaddocname-callback

**Comment by jandrieu** [comment]
Cool. I'll write something up.

On Tue, Jan 20, 2015, at 04:40 AM, Nuno Job wrote:
> You can just send the pull request with the fixes if you like.


> I think it would be best to have a general section explaining that
> this is the signature of all callback functions, instead of specifying
> one by one.


> What do you think?


> https://github.com/dscape/nano#dbheaddocname-callback


> — Reply to this email directly or view it on GitHub[1].

>

--
Joe Andrieu joe@andrieu.net +1(805)705-8651 http://blog.joeandrieu.com


Links:

  1. https://github.com/dscape/nano/issues/248#issuecomment-70647531
