### ISSUE TITLE
the 'since' paramter value for API nano.db.changes(name, [params], [callback])

### ISSUE THREAD

**Issue by asunflower** [dscape/nano#249]
Hi, what is the default value for the 'since' parameter? I excluded this parameter and expected the db.changes() API return me all change histories set, but it didn't. I also tried include {'since':0} but it didn't work either. With the 0 set, it returned one change only and randomly each time. So any document that describes nano supported parameters? The 'since' parameter seems not match what couchDB's has described.

Regards

**Comment by dscape** [comment]
Code should look like:

``` js
mydb.changes({since: 1}) 
```

See:
* https://github.com/dscape/nano/blob/master/lib/nano.js
* http://docs.couchdb.org/en/latest/api/database/changes.html#get--db-_changes

If you have code that does not work, please post and re-open the issue. If after creating the minimum viable test case you find this to be a bug, please add a test and send in a pull request.
