### ISSUE TITLE
View with params doesn't work...

### ISSUE THREAD

**Issue by kstankov** [dscape/nano#252]
Hi,

I am getting into trouble trying to call a view with params:
`dbPacks.view('packages','enabled', {keys:[key1]}, function (err, pack)    {..} `
doesn't work - it returns all documents in the view.
Same query works fine directly against CouchDB:
`http://localhost:5900/packages/_design/packages/_view/enabled?key=key1"`

Also, I cannot find a way to specify statkey and endkey. Is this missing from nano?
Is there way to pass params to the view simply as string? E.g. 'key="integral-key1"'

Many thanks in advance!

**Comment by jo** [comment]
The call you mentioned should work - have you assumed that the keys appear in the query string?

The `params` argument is used to generate the query string - except for the `keys` array, which will be sent as post body, see [CouchDBs Querying Options](http://wiki.apache.org/couchdb/HTTP_view_API#Querying_Options).

You can use every query option CouchDB understands in the `params` argument.
Note that  `startkey`, `endkey` and `key` gets JSON stringified by nano so you don't need to do that by yourself.

**Comment by jo** [comment]
Feel free to reopen if thats still an issue.
