### ISSUE TITLE
updateWithHandler doesn't work?

### ISSUE THREAD

**Issue by kstankov** [dscape/nano#255]
Hi,

db.updateWithHandler('test','SetValue', id, {field:'foo', value:'bar'},function (err, body){..}

doesn't seem to work against an update function:
function(doc,req) {doc[req.body.field]=req.body.value; return [doc, 'ok'];}

Tried with req.query.field/value as well - also no result.
The document revision is updated, but not the value - both field and value seem to be undefined. 
Couch DB version is 1.6.1.

This works:
curl -X PUT 'http://localhost:5984/test/_design/test/SetValue/_update/testdoc?field=foo&value=bar'

Am I doing something wrong?

BTW - the updates is called Ok, cause if I hardcode the field and value, doc is updated.

Thanks in advance!

**Comment by jo** [comment]
Note that `req.body` is - in contrast to `req.query` - not a parsed object but the raw request body. Thus you have to write

```js
function(doc,req) {
  var body = JSON.parse(req.body);
  doc[body.field] = body.value;
  return [doc, 'ok'];
}
```

See the stackoverflow question [Get data from json body in couchdb](http://stackoverflow.com/questions/25033259/get-data-from-json-body-in-couchdb) and [Document Update Handlers](http://wiki.apache.org/couchdb/Document_Update_Handlers) for general information about update handlers.

**Comment by kstankov** [comment]
Thanks a lot, works fine!
------------------------------------------------------------------------
*With best regards,*
Kiril Stankov

**Comment by dscape** [comment]
I'm currently on vacation. Is there anything I need to do here? Johannes
you have `npm own` right?

**Comment by jo** [comment]
yes:
```sh
[jo@localhost nano]$ npm own ls
dscape <nunojobpinto@gmail.com>
pgte <pedro.teixeira@gmail.com>
jo <schmidt@netzmerk.com>
```
