### ISSUE TITLE
TypeScript type definitions for nano

### ISSUE THREAD

**Issue by mictadlo** [dscape/nano#256]
Hi,
Any plans to provide TypeScript type definitions for nano on [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped)?

Mic

**Comment by hellboy81** [comment]
+1!!!

**Comment by hellboy81** [comment]
How can I contribute it (if I write ;-) ) to make available in Webstorm?

**Comment by mictadlo** [comment]
I think the best place would be here [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped).

**Comment by dscape** [comment]
Sorry im currently in vacation but will get back to you when back!

**Comment by jo** [comment]
Please reopen if still an issue

**Comment by eli-jordan** [comment]
I wen't looking for typescript definitions today, and they still don't seem to be available. So I think this is still a valid issue.

**Comment by ghost** [comment]
I am also unable to find the typescript definition files.  Hopefully it is still in the process?

**Comment by weber-d** [comment]
There is a package `@types/nano` but it doesn't seem to fit the documentation. For example, the doc say we've an attribute `db` where we can select the db like this:

```ts
var alice = nano.db.use('alice');
```
Intellisense in VS code doesn't show any property called `db`:

![Screenshot](https://i.imgur.com/bBl0RAm.png)
