### ISSUE TITLE
POST instead of GET for db.list

### ISSUE THREAD

**Issue by robertkeizer** [dscape/nano#257]
The request fails if a large query is passed in, such as specifying many `keys`.

http://docs.couchdb.org/en/latest/api/database/bulk-api.html#post--db-_all_docs

**Comment by robertkeizer** [comment]
I'm an idiot. Apologies. `fetchDocs` right besides that..

**Comment by jo** [comment]
Btw. `db.list` issues a POST if the `keys` property is used.
