### ISSUE TITLE
how to pass a parameter using db.change api

### ISSUE THREAD

**Issue by asunflower** [dscape/nano#259]
Hi,
I want to pass a parameter to my filter function, how can I achieve it using the nano.db.changes(dbName, params, callback) API so that I can have a filter function that uses that parameter...

{
  "_id": "_design/listeningOnDBChange",
  "filters": {
    "listenOnCity": "function(doc, city) {return (doc.city == city)}"
  }
}

'city' is a variable that I want to pass to filter function.

**Comment by jo** [comment]
You can query the changes feed with the city and access the query options from within your changes function.
See the section [Change Notifications in the book CouchDB The Definitive Guide](http://guide.couchdb.org/draft/notifications.html#filters) for more information.
