### ISSUE TITLE
Incorrect Json property name in documentation

### ISSUE THREAD

**Issue by elcomandantetibi** [dscape/nano#260]
In "**using cookie authentication**" there is no such object property `userCtx.user` rather `userCtx.name`. 
```
nano.session(function(err, session) {
  if (err) {
    return console.log('oh noes!')
  }

  console.log('user is %s and has these roles: %j',
    session.userCtx.user, session.userCtx.roles);
});
```
Furthermore, it probably should be specified that if the cookie changes, the user has to `require` a new `nano` object, i.e. there is no property to set the new cookie for an existing `nano` object.

Cheers.

**Comment by jo** [comment]
Thanks for reporting!

I fixed the property name doc with d8d8f70.
For the other issue please open another ticket, preferably with a test on how to reproduce the problem with the changing cookie.
