### ISSUE TITLE
Nano is moving to Apache CouchDB

### ISSUE THREAD

**Issue by garrensmith** [dscape/nano#265]
Hi all committers,

Nuno wants to donate Nano to the Apache CouchDB community. This is great news and will allow the CouchDB community to work closely with the Nano contributors to make sure Nano continues to be an excellent CouchDB library.

For this to happen we need the below listed contributors to sign the [CLA found here](http://www.apache.org/licenses/icla.txt) and email it to secretary@apache.org. Could you also leave a comment below to let us know when you have signed it or if you have previously signed the Apache CLA.

Thanks for your help

- [x] @dscape 
- [ ] @oleics 
- [x] @hydrozen 
- [x] @jo 
- [x] @bjnortier 
- [x] @streunerlein 
- [x] @ierceg 
- [x] @JayBeavers 
- [x] @svnlto 
- [ ] @chesles 
- [x] @alappe 
- [x] @grrtrr
- [ ] @boxxxie 
- [ ] Jonathan Mahoney
- [x] @pgte 
- [x] @tobie 
- [x] @jlank 
- [x] @klaemo 
- [ ] @joshperry 
- [x] @jkrems 
- [x] @daleharvey 
- [x] @perezd 
- [ ] @thiagoarrais 
- [ ] @mmalecki 
- [x] @PatrickHeneise 
- [ ] @fracek

**Comment by garrensmith** [comment]
Adding @janl @robertkowalski to this thread.

**Comment by klaemo** [comment]
I've just recently signed the CLA for a different project :)

**Comment by PatrickHeneise** [comment]
signed

**Comment by hydrozen** [comment]
signed

**Comment by jlank** [comment]
signed

**Comment by alappe** [comment]
√ signed…

**Comment by pgte** [comment]
signed

**Comment by grrtrr** [comment]
- [ ] @grrtrr
+ [X] @grrtrr

Signed :)

**Comment by ierceg** [comment]
signed

**Comment by bjnortier** [comment]
signed

**Comment by daleharvey** [comment]
I have previously signed an Apache SLA / am a CouchDB committer so should be good here

**Comment by jo** [comment]
signed

**Comment by jkrems** [comment]
signed

**Comment by dscape** [comment]
@jo major kudos for all the major contributions, effectively you were the lead of the project at this point :)

**Comment by svnlto** [comment]
signed

**Comment by janl** [comment]
*nudge the rest* (sorry others) — We’d love to get this closed <3

I looked through the straggler’s contributions, and not meaning any disrespect, from a legal perspective, we probably only need a CLA from:

- [ ] @perezd
- [ ] @thiagoarrais
- [ ] @streunerlein 
- [ ] @JayBeavers 

Thank you for your collaboration <3

**Comment by streunerlein** [comment]
Signed (sorry)

**Comment by tobie** [comment]
Sorry for the straggling, I've been on sick leave for over a month now, so running behind on email. Hereby granting you all rights to use `Buffer.byteLength` to… count the number of bytes in a string (afaik my only contribution to this otherwise very useful project). Still, signed and sent the CLA.

**Comment by jlank** [comment]
@tobie feel better!

**Comment by robertkowalski** [comment]
sorry to hear, tobie get well soon!

**Comment by janl** [comment]
get well soon, @tobie!

**Comment by JayBeavers** [comment]
Sent in.  I also release all copyright/ownership claims to my contributions to nano, please do as you wish.

**Comment by perezd** [comment]
Signed and emailed. I release all copyright/ownership claims to my contributions to nano, please do as you wish.

**Comment by garrensmith** [comment]
This is all done :+1:  :tada:

**Comment by thiagoarrais** [comment]
Sorry for the delay. For what it is worth, I've signed and emailed my CLA today.

**Comment by jo** [comment]
Thank you all!
