### ISSUE TITLE
`multipart.insert` not working when doc `name` is not specified

### ISSUE THREAD

**Issue by patriciagarcia** [dscape/nano#266]
Hi, 

creating a doc with attachments without specifying an `_id` for the doc (example below) is failing for me: 

```
alice.multipart.insert({ foo: 'bar' }, [{name: 'rabbit.png', data: data, content_type: 'image/png'}], function(err, body) {
        if (!err)
          console.log(body);
    });
```
I don't see any error, just the doc is not created in the database, but everything goes fine when I specify a doc name, as in here:

```
alice.multipart.insert({ foo: 'bar' }, [{name: 'rabbit.png', data: data, content_type: 'image/png'}], 'mydoc', function(err, body) {
        if (!err)
          console.log(body);
    });
```

According to the [documentation](https://github.com/dscape/nano#dbmultipartinsertdoc-attachments-params-callback) `params` is optional.

This might be a bug? Or am I doing something wrong?

Thanks!

**Comment by jo** [comment]
Hi @patriciagarcia, this indeed looks like a bug. Thanks for reporting!

**Comment by jo** [comment]
Currently only [`PUT /{db}/{docid}` with `multipart/related`](http://docs.couchdb.org/en/latest/api/document/common.html#creating-multiple-attachments) is supported in CouchDB.
There is a [JIRA ticket](https://issues.apache.org/jira/browse/COUCHDB-1685) demanding the POST.

Maybe nano could support the desired behaviour? Then we would need to feature detect it for upcoming CouchDB releases which supports this.

**Comment by jo** [comment]
In the meantime, I'll fix the docs.

**Comment by jo** [comment]
Closing this for now.
