### ISSUE TITLE
fetchRevs only fetching latest revision of document

### ISSUE THREAD

**Issue by embrown30** [dscape/nano#273]
I'm using the following to get all revs of a document but only one rev is returned:
docnames = {keys: ["somedocid"]}
db.fetchRevs(docnames, parms, function(err, docs){
				docs.rows.forEach(function(doc){
					if(!err){
						retdocs.push(doc.doc)
						console.log("fetchRevs: ", doc)
					}
					else{
						console.warn("Error getting revisions from database: ", err)
					}
				})
				callback(err,retdocs)
				
			});

I get this returned:

[
    {
        "_id": "2e6c63b6e6fcf9d686be8d32e0001a67",
        "_rev": "3-bca79e466ce6af40cf940518df9f84e7",
        "version": 0,
        "type": "page",
        "description": "page that is free flowing",
        "tennent": "EricabrDynasty",
        "name": null
    }
]

As you can see, _rev starts with three.. so there are other revisions of the document I'm not getting.
Is this what the function is supposed to do. Get ALL Revs of the document, not just the latest?
Thanks!

**Comment by jo** [comment]
`fetchRevs` is similar to fetch, except that `include_docs` is false.

What you want to achieve is not possible with a single query. However, you can retrieve all revisions of a _single_ document via `open_revs` set to `all`:
```js
db.get('somedocid', { open_revs: 'all' })
```

See CouchDBs documentation for [` GET /{db}/{docid}`](http://docs.couchdb.org/en/latest/api/document/common.html?highlight=get#get--db-docid).

**Comment by majidgolshadi** [comment]
Based on [couchdb doc](http://wiki.apache.org/couchdb/HTTP_Document_API#line-149) I try this code  but only return last data version
```nodejs
db.get('rabbit', {open_revs: ["7-6b29424ebe73f22bbef54611c302b849"]}, function(err, body) {
      console.log(body);
});
```
How we can fetch old version of a doc with `rev`?
