### ISSUE TITLE
db.follow ignores requestDefaults

### ISSUE THREAD

**Issue by gr2m** [dscape/nano#278]
Given 
1. a database exists at http://localhost:5984/db-with-security, which is only accessible when signed in
2. an admin exists with username `admin` and password `secret`

And I run this code

``` js
var nano = require('nano')

var db = nano({
  url: 'http://localhost:5984/db-with-security',
  requestDefaults: {
    auth: {
      user: 'admin',
      pass: 'secret'
    }
  }
})

db.info(function (error, info) {
  if (error) {
    return console.log(error)
  }
  console.log('info ok.')

  db.follow(function (error) {
    if (error) {
      return console.log(error)
    }

    console.log('follow ok.')
  })
})
```

I get this error

```
info ok.
[Error: Bad DB response: {"error":"unauthorized","reason":"You are not authorized to access this db."}]
```

~~Any idea if there is a way to work around this? It's giving my quite some trouble right now ... adding username & password to the CouchDB url aka `http://admin:secret@...` is not an option because the password can have all kind of special characters, couldn't get it to work~~

I've managed to add the user & pass to the CouchDB directly, so don't rely on `requestDefaults` anymore. But I'd still consider this an issue, from a user expectation perspective.

**Comment by carlosduclos** [comment]
I know this is kinda latte now, but this repository has been merged into apache/couchdb-nano. Is this issue still relevant? I am going to open a new issue in the new repository pointing to this one.
Please continue the discussion (and eventually any pull requests) [here](https://github.com/apache/couchdb-nano/issues/8)

**Comment by gr2m** [comment]
thanks for the triaging! I no longer use nano, so no problem for me any longer
