### ISSUE TITLE
fetch query does not  take effect

### ISSUE THREAD

**Issue by penzhan8451** [dscape/nano#282]
Hi,

I am using your 'nano' to operate cloudant db.  and I want to select out one record from the database.
But the query was not take effect, instead of return all records.   Could you please take a look at it?  

Below is my example code:
-------------------------------------------------------------
var CDB_URL = "https://xxxx:xxxx@xxxx.cloudant.com";
var nano = require('nano')(CDB_URL);
//nano.db.create
var dbname = 'connectors_';
var DB = nano.use(dbname);

DB.fetch({name:'salesforce'},function(err,data){
          if(err)  console.log('error in find: ' + err);
          else  {
                console.log(data.rows);
            };
          }
    });
-----------------------------------------------------------
The expected result is only one record returned,  but this will return all records.

This record looks like below:
---------------------------------------
{
  "_id": "a59f594e2d517ed2c542f8ab8abc7ae3",
  "_rev": "5-baf8cfb87e7e5d58d14da46b06ef6668",
  "name": "salesforce",
  "description": "this is salesforce connector",
  "baseUrl": "/",
  "icon": "/img/salesforce_44.png",
  "auth": {
    "type": "basic"
  },
  "models": [
    "Account",
    "Contact"
  ]
}
---------------------------------------

Thanks.

**Comment by jo** [comment]
`db.fetch(docnames, [params], [callback])` is for retrieving multiple records, use `db.get(docname, [params], [callback])` to get a single doc.
For the former you need to supply an array of docnames.
