### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by abhishiv** [dscape/nano#289]
I'm trying to make cloudant/nodejs-cloudant#82 which depends on nano to build via webpack.

There were many errors in the beginning, but I was able to make request etc work by having the following webpack config

```
	node: {
		console: 'empty',
		fs: 'empty',
		net: 'empty',
		tls: 'empty',
		__filename: true,
		__dirname: true
	}
```

However the only error left now is the following one, and it comes froms this [line](https://github.com/dscape/nano/blob/master/lib/nano.js#L761)

```
ERROR in ./~/cloudant/~/nano/lib/nano.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in /Users/abhishiv/work/gratico/grati.co/node_modules/cloudant/node_modules/nano/lib
 @ ./~/cloudant/~/nano/lib/nano.js 761:15-36
```

Can you consider replacing it with this

```
nano.version = require('../package.json').version;
```

That would allow me to use json-load webpack plugin in order to allow webpack to load it.

Thanks!

**Comment by jo** [comment]
Thank you! Please update the dependency to `6.1.5` which includes your fix.
