### ISSUE TITLE
source code of v6.2.0

### ISSUE THREAD

**Issue by targos** [dscape/nano#308]
Hello,

I just saw that v6.2.0 was published today.
Did you forget to push it on GitHub ?

cc @jhs

**Comment by jo** [comment]
Hi @targos, we are currently in a transfer process. the release was done on https://github.com/apache/couchdb-nano, which will be the repo.

I'll try to manually keep both in sync until the transfer is complete.

**Comment by targos** [comment]
All right, thanks!
I see the link in npm got fixed by https://github.com/apache/couchdb-nano/commit/596e9d1c6ca2eab3d8d91f684962298626d3fcc8
