### ISSUE TITLE
Is db.info internal or is part of the public api?

### ISSUE THREAD

**Issue by satazor** [dscape/nano#314]
`db.info()` is not documented but it's useful for me to retrieve the total number of documents. Is this function part of the public API?

Thanks.

**Comment by jo** [comment]
This is part of the official api.

Would be super cool if you could add it to the docs?

**Comment by satazor** [comment]
Here it is: #315

**Comment by satazor** [comment]
Bump.

**Comment by jo** [comment]
Thanks!
