### ISSUE TITLE
Question about JSON-encoded parameters...

### ISSUE THREAD

**Issue by mattgrande** [dscape/nano#339]
Hi there, I was doing a compare to see if I would have any problems upgrading from 6.1.5 to 6.2. It mostly looks fine, but one thing caught my eye...

In nano.js, currently line 511, there's this:

```
var paramsToEncode = ['counts', 'drilldown', 'group_sort', 'ranges', 'sort'];
```

Each of those query params are JSON encoded. As far as I can tell, those don't have a specific meaning in Couch, though... so why was that added?

https://github.com/dscape/nano/blob/master/lib/nano.js#L509

**Comment by jo** [comment]
I guess this is was meant to be used with [cloudant fulltext search](https://docs.cloudant.com/search.html): https://github.com/dscape/nano/commit/c03b5528b6b0759f7e001b722199f824163ad3a0
