### ISSUE TITLE
Does nano support purge?

### ISSUE THREAD

**Issue by enst** [dscape/nano#340]
http://docs.couchdb.org/en/stable/api/database/misc.html

Thanks,

**Comment by jo** [comment]
No, nano does not have an endpoint to purge. But you can use

``` js
nano.request({
  db: 'alice',
  path: '_purge',
  method: 'post',
  body: {
    'mydocid': ['rev-one', 'rev-two']
})
```

**Comment by dscape** [comment]
Feel free to send a PR, but make sure it goes to the version apache is keeping track of (here?)
