### ISSUE TITLE
Doubt on db access of live app

### ISSUE THREAD

**Issue by rmshkmr** [dscape/nano#353]
Using `var nano = require('nano')('http://localhost:5984');`  is fine. But for live application what to write instead of `http://localhost:5984`.

I hosted my node.js application in Amazon AWS using 
CouchDB - JSON based Web database powered by TurnKey GNU/Linux for database. 

My ipv4 public IP http://54.xxx.22.xxx/_utils shows my Database. confused what to write instead of  `http://localhost:5984` in code.

**Comment by jo** [comment]
Hi @rmshkmr `/_utils` is the Fauxton admin interface. Just write  `http://54.xxx.22.xxx`.

**Comment by rmshkmr** [comment]
Thanks. It Worked
