### ISSUE TITLE
errs not in dependencies

### ISSUE THREAD

**Issue by nomiddlename** [dscape/nano#70]
Package.json has errs as dev dependency instead of dependency. Causes the following error on require('nano'):

> require('nano')
> Error: Cannot find module 'errs'
>     at Function._resolveFilename (module.js:332:11)
>     at Function._load (module.js:279:25)
>     at Module.require (module.js:354:17)
>     at require (module.js:370:17)
>     at Object.<anonymous> (/Volumes/MacHD2/verticals/cs-whereis-poi-extract/node_modules/nano/nano.js:21:19)
>     at Module._compile (module.js:441:26)
>     at Object..js (module.js:459:10)
>     at Module.load (module.js:348:31)
>     at Function._load (module.js:308:12)
>     at Module.require (module.js:354:17)

**Comment by samdutton** [comment]
I got this for the **request** module as well.
